name: ASSIST Unit Tests (C)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get REBOUND and compile library
        env:
          REB_DIR: ../rebound
        run: | 
          git clone https://github.com/hannorein/rebound.git
          make
      - name: Download DE441 dataset
        run: |
          mkdir data
          wget -O datalinux_m13000p17000.441 https://ssd.jpl.nasa.gov/ftp/eph/planets/Linux/de441/linux_m13000p17000.441  
      - name: Reproduce Holman trajectory
        env:
          REB_DIR: ../../rebound
        working-directory: ./unit_tests/holman/
        run: |
          make
